import { FormConfig } from '@/components/forms/DynamicForm/types';

export const userFormConfig: FormConfig = {
  fields: [
    {
      name: 'firstname',
      label: 'n.name',
      type: 'text',
      placeholder: 'e.enterAValue',
      required: true,
    },
    {
      name: 'lastname',
      label: 'l.lastName',
      type: 'text',
      placeholder: 'e.enterAValue',
      required: true,
    },
    {
      name: 'email',
      label: 'e.email',
      type: 'email',
      placeholder: 'e.enterAValue',
      required: true,
    },
    {
      name: 'username',
      label: 'u.username',
      type: 'text',
      placeholder: 'e.enterAValue',
      required: false,
    },
    {
      name: 'password',
      label: 'p.password',
      type: 'password',
      placeholder: 'e.enterAValue',
      required: { create: true, edit: false },
      validation: {
        minLength: 8,
        minLengthMessage: 'p.passwordValidationMessage',
        pattern:
          /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[~£!@#$%^&*()\-_=+{}\[\]\\|:;"'<>,.?/])[A-Za-z\d~£!@#$%^&*()\-_=+{}\[\]\\|:;"'<>,.?/]{8,}$/,
        patternMessage: 'p.passwordValidationMessage',
      },
      errorTooltip: true,
      errorTooltipTrigger: 'r.reviewPassword',
    },
    {
      name: 'documentTypeId',
      label: 't.typeOfIdentificationDocument',
      type: 'select',
      placeholder: 's.selectAnOption',
      required: false,
      options: [],
    },
    {
      name: 'documentNumber',
      label: 'i.identificationDocument',
      type: 'text',
      placeholder: 'e.enterAValue',
      required: false,
    },
    {
      name: 'description',
      label: 'd.description',
      type: 'textarea',
      placeholder: 'e.enterAValue',
      required: false,
    },
    {
      name: 'city',
      label: 'c.city',
      type: 'text',
      placeholder: 'e.enterAValue',
      required: false,
    },
    {
      name: 'country',
      label: 'c.country',
      type: 'text',
      placeholder: 'e.enterAValue',
      required: false,
    },
    {
      name: 'institution',
      label: 'i.institution',
      type: 'text',
      placeholder: 'e.enterAValue',
      required: false,
    },
    {
      name: 'department',
      label: 'd.department',
      type: 'text',
      placeholder: 'e.enterAValue',
      required: false,
    },
    {
      name: 'phone',
      label: 'p.phone',
      type: 'text',
      placeholder: 'e.enterAValue',
      required: false,
    },
    {
      name: 'address',
      label: 'a.address',
      type: 'text',
      placeholder: 'e.enterAValue',
      required: false,
    },
    {
      name: 'status',
      label: 's.status',
      type: 'select',
      placeholder: 's.selectAnOption',
      required: false,
      options: [],
    },
    {
      name: 'company',
      label: 'c.company',
      type: 'select',
      placeholder: 's.selectAnOption',
      required: true,
      options: [],
    },
    {
      name: 'areaId',
      label: 'a.area',
      type: 'select',
      placeholder: 's.selectAnOption',
      required: false,
      options: [],
    },
    {
      name: 'positionId',
      label: 'p.position',
      type: 'select',
      placeholder: 's.selectAnOption',
      required: false,
      options: [],
    },
  ],
  columns: 2,
};
