import { RecruitmentAndSelection } from './recruitmentAndSelection.types';

export const recruitmentAndSelectionByRoute: Record<string, RecruitmentAndSelection[]> = {
  'Fundamentos del Reclutamiento y Selección': [
    {
      code: 'N0001',
      name: 'Introducción al Reclutamiento y Selección de Personal',
      trainingRoute: 'Fundamentos del Reclutamiento y Selección',
      startDate: '13/06/2025',
      endDate: '---',
      status: 'Completado',
    },
    {
      code: 'N0002',
      name: 'Rol del Reclutador en la Organización',
      trainingRoute: 'Fundamentos del Reclutamiento y Selección',
      startDate: '05/07/2025',
      endDate: '---',
      status: 'Iniciado',
    },
    {
      code: 'N0003',
      name: 'Tipos de Contratación y Modalidades Laborales',
      trainingRoute: 'Fundamentos del Reclutamiento y Selección',
      startDate: '---',
      endDate: '---',
      status: 'Sin iniciar',
    },
    {
      code: 'N0004',
      name: 'Ética y Confidencialidad en Procesos de Selección',
      trainingRoute: 'Fundamentos del Reclutamiento y Selección',
      startDate: '---',
      endDate: '---',
      status: 'Sin iniciar',
    },
  ],

  'Atracción de Talento y Employer Branding': [
    {
      code: 'N0101',
      name: 'Employer Branding y Marca Empleadora',
      trainingRoute: 'Atracción de Talento y Employer Branding',
      startDate: '10/08/2025',
      endDate: '---',
      status: 'Iniciado',
    },
    {
      code: 'N0102',
      name: 'Canales Digitales de Atracción de Talento',
      trainingRoute: 'Atracción de Talento y Employer Branding',
      startDate: '---',
      endDate: '---',
      status: 'Sin iniciar',
    },
    {
      code: 'N0102',
      name: 'Canales Digitales de Atracción de Talento',
      trainingRoute: 'Atracción de Talento y Employer Branding',
      startDate: '15/08/2025',
      endDate: '---',
      status: 'Iniciado',
    },
  ],

  'Evaluación y Entrevista de Candidatos': [
    {
      code: 'N0201',
      name: 'Entrevistas por Competencias',
      trainingRoute: 'Evaluación y Entrevista de Candidatos',
      startDate: '01/09/2025',
      endDate: '---',
      status: 'Completado',
    },
    {
      code: 'N0202',
      name: 'Pruebas Técnicas y Psicométricas',
      trainingRoute: 'Evaluación y Entrevista de Candidatos',
      startDate: '---',
      endDate: '---',
      status: 'Sin iniciar',
    },
    {
      code: 'N0203',
      name: 'Diseño de Guías de Entrevista Estructurada',
      trainingRoute: 'Evaluación y Entrevista de Candidatos',
      startDate: '---',
      endDate: '---',
      status: 'Sin iniciar',
    },
    {
      code: 'N0204',
      name: 'Evaluación de Competencias Técnicas',
      trainingRoute: 'Evaluación y Entrevista de Candidatos',
      startDate: '20/09/2025',
      endDate: '---',
      status: 'Iniciado',
    },
    {
      code: 'N0205',
      name: 'Análisis de Resultados y Toma de Decisiones',
      trainingRoute: 'Evaluación y Entrevista de Candidatos',
      startDate: '---',
      endDate: '---',
      status: 'Sin iniciar',
    },
  ],

  'Herramientas Digitales para Reclutamiento': [
    {
      code: 'N0301',
      name: 'ATS y Automatización de Procesos',
      trainingRoute: 'Herramientas Digitales para Reclutamiento',
      startDate: '15/10/2025',
      endDate: '---',
      status: 'Sin iniciar',
    },
    {
      code: 'N0302',
      name: 'Uso de LinkedIn Recruiter y Plataformas de Empleo',
      trainingRoute: 'Herramientas Digitales para Reclutamiento',
      startDate: '---',
      endDate: '---',
      status: 'Completado',
    },
    {
      code: 'N0303',
      name: 'Análisis de Métricas y KPIs de Reclutamiento Digital',
      trainingRoute: 'Herramientas Digitales para Reclutamiento',
      startDate: '05/11/2025',
      endDate: '---',
      status: 'Iniciado',
    },
  ],
};
