name: Run tests

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Configure GitHub Packages authentication
        run: |
          echo "@soportephonix:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "@youniversityrepo:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PACKAGES_TOKEN_PHONIX_UI }}" >> .npmrc
          echo "Token set: ${#PACKAGES_TOKEN_PHONIX_UI} chars"
        env:
          PACKAGES_TOKEN_PHONIX_UI: ${{ secrets.PACKAGES_TOKEN_PHONIX_UI }}

      - name: Set Yarn registry to public npm
        run: yarn config set registry https://registry.npmjs.org

      - name: Install project dependencies
        run: yarn install

      # - name: Run tests
      #   run: yarn run test:ci
